version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: financial_bot_db
    environment:
      POSTGRES_DB: financial_bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: